version: "3"

volumes:
  dolibarr_html:
  dolibarr_docs:
  dolibarr_db:

services:

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - dolibarr_db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: dolibarr
        MYSQL_USER: dolibarr
        MYSQL_PASSWORD: dolibarr
        MYSQL_ROOT_PASSWORD: root

  dolibarr:
    image: upshift/dolibarr:latest
    restart: always
    depends_on:
        - mariadb
    ports:
        - "8080:80"
    environment:
        DOLI_DB_HOST: mariadb
        DOLI_DB_NAME: dolibarr
        DOLI_DB_USER: dolibarr
        DOLI_DB_PASSWORD: dolibarr
        DOLI_DB_CHARACTER_SET: utf8
    volumes:
        - dolibarr_html:/var/www/html
        - dolibarr_docs:/var/www/documents
networks:
  sae51:
    driver: bridge
