version: "3"

services:
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        volumes:
            - ./sql:/var/lib/mysql
            # J'ajoute le volume data sur mon système. 
            # En faisant ça, même si je supprime l'intégralité
            # de mes conteneurs et volumes 
            #( commande docker system prune par exemple )
            #, je ne perdrai pas mes données

    web:
        image: tuxgasy/dolibarr
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_MODULES: modSociete
            DOLI_URL_ROOT: 'http://0.0.0.0'
            PHP_INI_DATE_TIMEZONE: 'Europe/Paris'
            DOLI_ADMIN_LOGIN: calvin
            DOLI_ADMIN_PASSWORD: arrive
            DOLI_CRON: 0
        ports:
            - "80:80"
        links:
            - mariadb
networks:
  sae51:
    driver: bridge
