# Utilisez une image Debian officielle comme base
FROM debian:11

# Mise à jour du système et installation des dépendances nécessaires
RUN apt-get update 
RUN apt-get install -y build-essential python3 python3-pip

#installation des paquet python flask
RUN pip3 install Flask flask-mysqldb mysql-connector-python flask-bcrypt

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copie du script Python
COPY app.py .

# Copiez le répertoire templates (qui contient newuser.html) dans le conteneur
COPY templates /app/templates

# Exposez le port 5000 pour Flask
EXPOSE 5000

# Commande pour exécuter l'application Flask
CMD ["flask", "run", "--host=0.0.0.0"]