Table pc {
  id integer [primary key]
  id_os varchar
  id_ram varchar
  date_achat varchar
  id_marque integer
  id_logiciel integer
}

Table users {
  id integer [primary key]
  nom varchar
  prenom varchar
  id_pc integer
}

Table logiciels {
  id integer [primary key]
  nom varchar
  version varchar
}

Table maintenance {
  id integer [primary key]
  description text
  date date
  id_technicien integer
  id_pc integer
}

Table marque {
  id integer [primary key]
  nom varchar
}

Table technicien {
  id integer [primary key]
  nom varchar
  prenom varchar
}

Table os {
  id integer [primary key]
  nom_os varchar
}

Table ram {
  id integer [primary key]
  ram_gb integer
}

Ref: "pc"."id" < "users"."id_pc"

Ref: "pc"."id" < "maintenance"."id_pc"

Ref: "logiciels"."id" < "pc"."id_logiciel"

Ref: "technicien"."id" < "maintenance"."id_technicien"

Ref: "marque"."id" < "pc"."id_marque"

Ref: "ram"."id" < "pc"."id_ram"

Ref: "os"."id" < "pc"."id_os"
