USE sae51;

LOAD DATA INFILE '/srv/csv/users.csv' INTO TABLE users FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/os.csv' INTO TABLE os FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/ram.csv' INTO TABLE ram FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/marque.csv' INTO TABLE marque FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/logiciels.csv' INTO TABLE logiciels FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/technicien.csv' INTO TABLE technicien FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/maintenance.csv' INTO TABLE maintenance FIELDS TERMINATED BY ';' IGNORE 1 ROWS;

LOAD DATA INFILE '/srv/csv/pc.csv' INTO TABLE pc FIELDS TERMINATED BY ';' IGNORE 1 ROWS;
